local wilson_attack = 34
local total_day_time = TUNING.TOTAL_DAY_TIME

TUNING.MOONGLASSMACHETE =
    {
        EFFECTIVENESS = 3,
        CONSUMPTION = 1.5,
        DAMAGE = wilson_attack,
    }


-- TUNING.OBSIDIANBOAT_HEALTH = 400
-- TUNING.OBSIDIANBOAT_PERISHTIME = total_day_time*5
-- TUNING.OBSIDIANBOAT_SANITY_DRAIN = 0
-- TUNING.OBSIDIANBOAT_SPEED = 0
-- TUNING.OBSIDIANBOAT_WAVEBOOST = 20
-- TUNING.OBSIDIANBOAT_LEAKING_HEALTH = 40
-- TUNING.OBSIDIANBOAT_HIT_IMMUNITY = 4
